### ISSUE TITLE
如何使用？

### ISSUE THREAD

**Issue by nosqldb** [wakaryry/editorMd#1]
只有css，js呢？不变？如何使用

**Comment by wakaryry** [comment]
引入即可

其它不变

**Comment by wakaryry** [comment]
将codemirror那个css文件替换掉原同名文件
在css的引入处后面引入custom.css

我记得后面我修改过几次，现在这个不是最新的。

我回去看看

**Comment by nosqldb** [comment]
thanks.重新开个分支呗，都加上，editorMd原来界面东西太多了
